Create
Ilia28593/java-shareit pull request #2
Opened 2023-06-25 14:05 UTC by Ilia28593

2023-06-26 12:44 UTC, krylov-sergey-sergeevich requested changes
Привет

- Название pr не говорящее это плохо
- Почему в pr так мало кода? Он был раньше залит? Почему не в это ветке? Проверять очень очень неудобно и комментарии оставлять

Код трудно проверить просьба пересоздать pr правильно

2023-06-26 13:38 UTC, Ilia28593 commented
Добрый день, я к сожалению написал ветку быстро, и толком не озаботился о комитах

2023-06-27 06:33 UTC, krylov-sergey-sergeevich approved these changes
Привет, хорошо в этой задаче ставится зачет, НО в следующем дз ожидай замечания и по предыдущей работе. Больше таких PR зачитывать не буду тк его крайне неудобно проверять и по сути это надо было переделывать в нормальный PR.

2023-06-27 06:33 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/service/CrudService.java
> +public abstract class CrudService<T extends Entity> extends Service {
Переусложненная структура я бы от такой избавился. И сразу вопрос сам придумал?)

2023-06-27 06:49 UTC, Ilia28593 commented on src/main/java/ru/practicum/shareit/user/service/CrudService.java
> +public abstract class CrudService<T extends Entity> extends Service {
на групповом подглядел структуру но немного переделал под себя, довольно удобно, хотя я ещё её доделываю

2023-08-01 07:34 UTC, merged