Add bookings
Ilia28593/java-shareit pull request #4
Opened 2023-08-01 07:35 UTC by Ilia28593

2023-08-01 18:09 UTC, krylov-sergey-sergeevich requested changes
Привет, хорошая работа, давай чутка доработаем по тому что отписал

p.s еще 1 проверка не прошла ее надо пофиксить

2023-08-01 18:09 UTC, krylov-sergey-sergeevich commented on pom.xml
> +			<version>32.0.1-jre</version>
Зачем эта зависимость?

2023-08-01 18:09 UTC, krylov-sergey-sergeevich commented on pom.xml
> +			<version>2.6.1</version>
зачем указывать версию если у нас есть spring-boot-parent

2023-08-01 18:09 UTC, krylov-sergey-sergeevich commented on pom.xml
> +			<version>2.6.1</version>
зачем указывать версию если у нас есть spring-boot-parent

2023-08-01 18:09 UTC, krylov-sergey-sergeevich commented on pom.xml
> +			<version>5.4.24.Final</version>
зачем зависимость хибера?

2023-08-01 18:09 UTC, krylov-sergey-sergeevich commented on pom.xml
> +            <version>4.13.2</version>
4 а чего не 5?

2023-08-01 18:09 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingResponseDto createBooking(@RequestHeader("X-Sharer-User-Id") long userId,
"X-Sharer-User-Id" эта штука много где повторяется рекомендую ее вынести в класс Constants и использовать переменную

2023-08-01 18:09 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +        return getClass().hashCode();
А есть понимание в чем такой подход опасен?

2023-08-01 18:09 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/repository/service/BookingServiceImpl.java
> +    public Booking create(long idUser, long idItem, Booking entity) {
комменты лучше удалять постепенно когда уже код рабочий

2023-08-01 18:09 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/config/DataConfig.java
> +public class DataConfig {
А без этого класса не работает? Мы же стартеры используем

2023-08-01 18:09 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        Comment i = itemService.createComment(userId,itemId,comment);
i название прям говорящее... )

2023-08-01 18:09 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return convertorComment.convert(i);
convert(i) тоже так себе

2023-08-01 18:09 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +    created      timestamp
TIMESTAMP WITHOUT TIME ZONE NOT NULL,

2023-08-01 18:09 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/practicum/shareit/UserTest.java
> +//public class UserTest {
В каком состояние?)

2023-08-03 06:14 UTC, Ilia28593 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +        return getClass().hashCode();
да может быть коллизия

2023-08-03 06:55 UTC, Ilia28593 commented on pom.xml
> +			<version>32.0.1-jre</version>
тестил для работы, не туда закинул

2023-08-03 07:18 UTC, Ilia28593 commented on src/test/java/ru/practicum/shareit/UserTest.java
> +//public class UserTest {
да прислали мне тз для устройства, я выпал немного, всё тестировал здесь)

2023-08-03 07:29 UTC, Ilia28593 commented on src/main/java/ru/practicum/shareit/config/DataConfig.java
> +public class DataConfig {
Сейчас да, но я там подключал 2 дб

2023-08-04 08:31 UTC, closed without merging